/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Website;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author SHINU
 */
public class AdminFrame extends javax.swing.JFrame {

    public AdminFrame() {
        initComponents();
        loadCards();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jDialog1 = new javax.swing.JDialog();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        TitleLabel = new javax.swing.JLabel();
        LogoutButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        AdminTab = new javax.swing.JTabbedPane();
        AddPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PriceField = new javax.swing.JTextField();
        CardNameText = new javax.swing.JTextField();
        ImageField = new javax.swing.JTextField();
        cardTypeCombo = new javax.swing.JComboBox<>();
        ChooseURLButton = new javax.swing.JButton();
        PreviewLabel = new javax.swing.JLabel();
        AddCardButton = new javax.swing.JButton();
        preview2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DescriptionField = new javax.swing.JTextArea();
        DescriptionLabel = new javax.swing.JLabel();
        DeletePanel = new javax.swing.JPanel();
        ScrollPane = new javax.swing.JScrollPane();
        DeleteTable = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        EnableButton = new javax.swing.JButton();
        DisableButton = new javax.swing.JButton();
        UpdatePanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        CardIdField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ColumnCombo = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextField = new javax.swing.JTextArea();
        UpdateButton = new javax.swing.JButton();
        ViewSalePanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        SaleTable = new javax.swing.JTable();
        SaleButton = new javax.swing.JButton();
        MonthField = new javax.swing.JTextField();
        YearField = new javax.swing.JTextField();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(207, 215, 255));
        jPanel2.setToolTipText("");

        TitleLabel.setBackground(new java.awt.Color(207, 215, 255));
        TitleLabel.setFont(new java.awt.Font("Edwardian Script ITC", 1, 48)); // NOI18N
        TitleLabel.setForeground(new java.awt.Color(0, 0, 102));
        TitleLabel.setText("Geetha RaniCards");
        TitleLabel.setOpaque(true);

        LogoutButton.setBackground(new java.awt.Color(207, 215, 255));
        LogoutButton.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        LogoutButton.setForeground(new java.awt.Color(255, 255, 255));
        LogoutButton.setBorder(null);
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(207, 215, 255));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\SHINU\\OneDrive\\문서\\miniproject\\wedding cards\\Icons\\logoutbtn.png")); // NOI18N
        jButton1.setBorder(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 946, Short.MAX_VALUE)
                .addComponent(LogoutButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(LogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 70));

        AdminTab.setBackground(new java.awt.Color(207, 215, 255));

        AddPanel.setBackground(new java.awt.Color(212, 222, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Card Name ");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Card Type");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Card Price");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("Image");

        PriceField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        CardNameText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        ImageField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        cardTypeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hindu", "Christian", "Muslim" }));
        cardTypeCombo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        cardTypeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardTypeComboActionPerformed(evt);
            }
        });

        ChooseURLButton.setBackground(new java.awt.Color(32, 47, 149));
        ChooseURLButton.setForeground(new java.awt.Color(255, 255, 255));
        ChooseURLButton.setText("Choose URL");
        ChooseURLButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        ChooseURLButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChooseURLButtonActionPerformed(evt);
            }
        });

        PreviewLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        AddCardButton.setBackground(new java.awt.Color(32, 47, 149));
        AddCardButton.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        AddCardButton.setForeground(new java.awt.Color(255, 255, 255));
        AddCardButton.setText("Add Card");
        AddCardButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null));
        AddCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCardButtonActionPerformed(evt);
            }
        });

        preview2.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        preview2.setText("Image Preview");

        DescriptionField.setColumns(20);
        DescriptionField.setRows(5);
        DescriptionField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane1.setViewportView(DescriptionField);

        DescriptionLabel.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        DescriptionLabel.setText("Description");

        javax.swing.GroupLayout AddPanelLayout = new javax.swing.GroupLayout(AddPanel);
        AddPanel.setLayout(AddPanelLayout);
        AddPanelLayout.setHorizontalGroup(
            AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ImageField, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                        .addComponent(CardNameText, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                        .addComponent(PriceField))
                    .addComponent(cardTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChooseURLButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(168, 168, 168)
                .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(preview2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(AddPanelLayout.createSequentialGroup()
                        .addComponent(PreviewLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 153, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(AddPanelLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(AddCardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AddPanelLayout.setVerticalGroup(
            AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddPanelLayout.createSequentialGroup()
                .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(preview2)
                            .addComponent(DescriptionLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PreviewLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGap(112, 112, 112))
                    .addGroup(AddPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CardNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cardTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AddPanelLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ImageField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))))
                .addComponent(ChooseURLButton)
                .addGap(18, 18, 18)
                .addComponent(AddCardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        AdminTab.addTab("Add Cards", AddPanel);

        DeletePanel.setBackground(new java.awt.Color(212, 222, 255));

        DeleteTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Card ID", "Card Name", "Status"
            }
        ));
        ScrollPane.setViewportView(DeleteTable);

        jLabel12.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel12.setText("DELETE  CARD");

        EnableButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        EnableButton.setText("ENABLE CARD");
        EnableButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        EnableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnableButtonActionPerformed(evt);
            }
        });

        DisableButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DisableButton.setText("DISABLE CARD");
        DisableButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        DisableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisableButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DeletePanelLayout = new javax.swing.GroupLayout(DeletePanel);
        DeletePanel.setLayout(DeletePanelLayout);
        DeletePanelLayout.setHorizontalGroup(
            DeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DeletePanelLayout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addComponent(ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1097, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(194, 194, 194))
            .addGroup(DeletePanelLayout.createSequentialGroup()
                .addGroup(DeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DeletePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DeletePanelLayout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(EnableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(383, 383, 383)
                        .addComponent(DisableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DeletePanelLayout.setVerticalGroup(
            DeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeletePanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(DeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EnableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DisableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        AdminTab.addTab("Delete Cards", DeletePanel);

        UpdatePanel.setBackground(new java.awt.Color(212, 222, 255));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setText("Enter Card ID ");

        CardIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CardIdFieldActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel7.setText("Choose Column");

        ColumnCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Card Name", "Card Type", "Description", "Price" }));
        ColumnCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColumnComboActionPerformed(evt);
            }
        });

        TextField.setColumns(20);
        TextField.setRows(5);
        TextField.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Enter Data to change", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 3, 14))); // NOI18N
        jScrollPane2.setViewportView(TextField);

        UpdateButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        UpdateButton.setText("UPDATE");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UpdatePanelLayout = new javax.swing.GroupLayout(UpdatePanel);
        UpdatePanel.setLayout(UpdatePanelLayout);
        UpdatePanelLayout.setHorizontalGroup(
            UpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdatePanelLayout.createSequentialGroup()
                .addGroup(UpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UpdatePanelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(UpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                        .addGap(83, 83, 83)
                        .addGroup(UpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CardIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ColumnCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(UpdatePanelLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UpdatePanelLayout.createSequentialGroup()
                        .addGap(377, 377, 377)
                        .addComponent(UpdateButton)))
                .addContainerGap(595, Short.MAX_VALUE))
        );
        UpdatePanelLayout.setVerticalGroup(
            UpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdatePanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(UpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CardIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(UpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ColumnCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(UpdateButton)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        AdminTab.addTab("Update Cards", UpdatePanel);

        ViewSalePanel.setBackground(new java.awt.Color(212, 222, 255));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel9.setText("VIEW SALES ");

        SaleTable.setFont(new java.awt.Font("Segoe UI Emoji", 3, 14)); // NOI18N
        SaleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Order ID", "Amount", "Quantity", "Date"
            }
        ));
        SaleTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane4.setViewportView(SaleTable);

        SaleButton.setBackground(new java.awt.Color(51, 51, 255));
        SaleButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SaleButton.setForeground(new java.awt.Color(255, 255, 255));
        SaleButton.setText("View Sale");
        SaleButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        SaleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaleButtonActionPerformed(evt);
            }
        });

        MonthField.setBackground(new java.awt.Color(212, 222, 255));
        MonthField.setForeground(new java.awt.Color(255, 255, 255));
        MonthField.setText("MM");
        MonthField.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Month", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 3, 14))); // NOI18N
        MonthField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                MonthFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                MonthFieldFocusLost(evt);
            }
        });

        YearField.setBackground(new java.awt.Color(212, 222, 255));
        YearField.setForeground(new java.awt.Color(255, 255, 255));
        YearField.setText("YYYY");
        YearField.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Year", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 3, 14))); // NOI18N
        YearField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                YearFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                YearFieldFocusLost(evt);
            }
        });

        javax.swing.GroupLayout ViewSalePanelLayout = new javax.swing.GroupLayout(ViewSalePanel);
        ViewSalePanel.setLayout(ViewSalePanelLayout);
        ViewSalePanelLayout.setHorizontalGroup(
            ViewSalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewSalePanelLayout.createSequentialGroup()
                .addGroup(ViewSalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewSalePanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(ViewSalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ViewSalePanelLayout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(YearField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(MonthField, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(SaleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(ViewSalePanelLayout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 852, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(317, Short.MAX_VALUE))
        );
        ViewSalePanelLayout.setVerticalGroup(
            ViewSalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewSalePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ViewSalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(YearField, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MonthField, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        AdminTab.addTab("View Sales", ViewSalePanel);

        getContentPane().add(AdminTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1390, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        // TODO add your handling code here:
        int confirmLogout = JOptionPane.showConfirmDialog(this,
            "Are you sure you want to logout?",
            "Logout Confirmation",
            JOptionPane.YES_NO_OPTION);

        if (confirmLogout == JOptionPane.YES_OPTION) {
            
            this.dispose();  
            new MainFrame().setVisible(true); 
        }
    }//GEN-LAST:event_LogoutButtonActionPerformed
private File selectedFile;
    private void AddCardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCardButtonActionPerformed
        
        String cardName = CardNameText.getText();
    String cardType = (String) cardTypeCombo.getSelectedItem();
    String cardPrice = PriceField.getText();
    String descriptions = DescriptionField.getText();

    if (cardName.isEmpty() || cardPrice.isEmpty() || selectedFile == null || descriptions.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill all fields and select an image.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

        try {
            saveCardToDatabase(cardName, cardType, cardPrice, selectedFile.getAbsolutePath(), descriptions);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminFrame.class.getName()).log(Level.SEVERE, null, ex);
        }   
    CardNameText.setText("");
    PriceField.setText("");
    ImageField.setText("");
    DescriptionField.setText("");
    PreviewLabel.setIcon(null);
    selectedFile = null;
    }//GEN-LAST:event_AddCardButtonActionPerformed

    private void ChooseURLButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChooseURLButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChoose =  new JFileChooser();
        fileChoose.setFileFilter(new FileNameExtensionFilter("Image Files", "jpg", "jpeg", "png"));
        
        int result = fileChoose.showOpenDialog(this);
        if(result == JFileChooser.APPROVE_OPTION){
               selectedFile = fileChoose.getSelectedFile();
               String imgpath = selectedFile.getAbsolutePath();
        ImageIcon cardImage = new ImageIcon(selectedFile.getAbsolutePath());
            Image img = cardImage.getImage().getScaledInstance(200, 200, Image.SCALE_SMOOTH);
            PreviewLabel.setIcon(new ImageIcon(img));
            ImageField.setText(imgpath);
        }
    }//GEN-LAST:event_ChooseURLButtonActionPerformed
    private Connection conn ;
    private void saveCardToDatabase(String name, String type, String price, String imagePath, String descriptions) throws ClassNotFoundException {
        try {
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            
            String url = "jdbc:mysql://localhost:3306/project?useSSL=false&allowPublicKeyRetrieval=true";  
            String user = "root"; 
            String password = "Shin@maya";  

            
            conn = DriverManager.getConnection(url, user, password);
            String query = "INSERT INTO cards (name, type, price, image_path,descriptions) VALUES (?, ?, ?, ?, ?)";

            PreparedStatement pstmt = conn.prepareStatement(query);
            pstmt.setString(1, name);
            pstmt.setString(2, type);
            pstmt.setFloat(3, Float.parseFloat(price));
            pstmt.setString(4, imagePath);
            pstmt.setString(5, descriptions);

            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Card added successfully!");
            conn.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage());
        }
    }
    
    
    private void cardTypeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardTypeComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardTypeComboActionPerformed

    private void CardIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CardIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CardIdFieldActionPerformed

    private void ColumnComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColumnComboActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ColumnComboActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
        String cardId = CardIdField.getText().trim();
        String selectedColumn = ColumnCombo.getSelectedItem().toString();
        String newValue = TextField.getText().trim();

        if (cardId.isEmpty() || newValue.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter Card ID and Data to change.");
            return;
        }

        String dbColumn = " ";
        switch (selectedColumn) {
            case "Card Name": 
                dbColumn = "name"; 
                break;
            case "Card Price": 
                dbColumn = "price"; 
                break;
            case "Card Image": 
                dbColumn = "image_path"; 
                break;
            case "Card Type": 
                dbColumn = "type"; 
                break;
            case "Description":
                dbColumn = "descriptions";
                break;
            default:
                JOptionPane.showMessageDialog(null, "Invalid column selected.");
                return;
        }

        try {
            Connection conn = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/project?useSSL=false&allowPublicKeyRetrieval=true", "root", "Shin@maya");
            String sql = "UPDATE cards SET " + dbColumn + " = ? WHERE card_id = ?";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, newValue);
            stmt.setString(2, cardId);

            int rowsAffected = stmt.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(null, "Card updated successfully.");
            } else {
                JOptionPane.showMessageDialog(null, "Card ID not found.");
            }

            stmt.close();
            conn.close();

        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error updating card: " + ex.getMessage());
        }
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void SaleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaleButtonActionPerformed
        // TODO add your handling code here:
        String year = YearField.getText();
        String month = MonthField.getText();
        loadSalesByMonthYear(SaleTable, year, month); 

    }//GEN-LAST:event_SaleButtonActionPerformed

    private void YearFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_YearFieldFocusGained
        // TODO add your handling code here:
        if(YearField.getText().equals("YYYY")){
            YearField.setText("");
            YearField.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_YearFieldFocusGained

    private void YearFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_YearFieldFocusLost
        // TODO add your handling code here:
        if(YearField.getText().isEmpty()){
            YearField.setText("YYYY");
            YearField.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_YearFieldFocusLost

    private void MonthFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MonthFieldFocusGained
        // TODO add your handling code here:
        if(MonthField.getText().equals("MM")){
            MonthField.setText("");
            MonthField.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_MonthFieldFocusGained

    private void MonthFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MonthFieldFocusLost
        // TODO add your handling code here:
         if(MonthField.getText().isEmpty()){
            MonthField.setText("MM");
            MonthField.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_MonthFieldFocusLost

    private void EnableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnableButtonActionPerformed
        // TODO add your handling code here:
        int cardId = getSelectedCardId();
            if (cardId != -1) {
                updateCardAvailability(cardId, 1); 
            }
    }//GEN-LAST:event_EnableButtonActionPerformed

    private void DisableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisableButtonActionPerformed
        // TODO add your handling code here:
        int cardId = getSelectedCardId();
            if (cardId != -1) {
                updateCardAvailability(cardId, 0); 
            }
    }//GEN-LAST:event_DisableButtonActionPerformed

   private void loadCards() {
        try (Connection conn = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/project?useSSL=false&allowPublicKeyRetrieval=true",
                "root", "Shin@maya")) {
            DefaultTableModel tableModel = (DefaultTableModel) DeleteTable.getModel(); 
            tableModel.setRowCount(0); // Clear previous rows

            String sql = "SELECT card_id, name, available FROM cards";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);

            while (rs.next()) {
                int cardId = rs.getInt("card_id");
                String cardName = rs.getString("name");
                int available = rs.getInt("available");

                String availableStatus = (available == 1) ? "Available" : "Unavailable";

                tableModel.addRow(new Object[]{cardId, cardName, availableStatus});
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
        }
    }

private int getSelectedCardId() {
    int selectedRow = DeleteTable.getSelectedRow();
    
    if (selectedRow != -1) {
        
        Object cardIdObj = DeleteTable.getValueAt(selectedRow, 0);
        if (cardIdObj != null) {
            return Integer.parseInt(cardIdObj.toString()); 
        } else {
            JOptionPane.showMessageDialog(this, "Card ID is null. Please select a valid row.");
            return -1;
        }
    } else {
        JOptionPane.showMessageDialog(this, "Please select a card first.");
        return -1;
    }
}


    private void updateCardAvailability(int cardId, int availableStatus) {
        try (Connection conn = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/project?useSSL=false&allowPublicKeyRetrieval=true",
                "root", "Shin@maya")) {

            String sql = "UPDATE cards SET available = ? WHERE card_id = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setInt(1, availableStatus);
            pst.setInt(2, cardId);

            int rowsUpdated = pst.executeUpdate();

            if (rowsUpdated > 0) {
                String message = (availableStatus == 1) ? "Card enabled successfully!" : "Card disabled successfully!";
                JOptionPane.showMessageDialog(this, message);
                loadCards(); 
            } else {
                JOptionPane.showMessageDialog(this, "Failed to update card availability.");
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
        }
    }

    public void loadSalesByMonthYear(JTable table, String yearStr, String monthStr) {
    if (yearStr.isEmpty() || monthStr.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please enter both Year and Month.");
        return;
    }

    try {
        int year = Integer.parseInt(yearStr);
        int month = Integer.parseInt(monthStr);

        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/project?useSSL=false&allowPublicKeyRetrieval=true", "root", "Shin@maya"); 

        PreparedStatement stmt = conn.prepareStatement(
            "SELECT order_id, total_price, quantity, order_date FROM orders WHERE YEAR(order_date) = ? AND MONTH(order_date) = ?"
        );
        stmt.setInt(1, year);
        stmt.setInt(2, month);
        var rs = stmt.executeQuery();

        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new Object[]{"Order ID", "Amount", "Quantity", "Date"});

        while (rs.next()) {
            String orderId = rs.getString("order_id");
            double amount = rs.getDouble("total_price");
            int qty = rs.getInt("quantity");
            Date date = rs.getDate("order_date");

            model.addRow(new Object[]{orderId, amount, qty, date});
        }

        table.setModel(model);

    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(null, "Year and Month must be numeric values.");
    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
    }
}

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(smaple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(smaple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(smaple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(smaple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCardButton;
    private javax.swing.JPanel AddPanel;
    private javax.swing.JTabbedPane AdminTab;
    private javax.swing.JTextField CardIdField;
    private javax.swing.JTextField CardNameText;
    private javax.swing.JButton ChooseURLButton;
    private javax.swing.JComboBox<String> ColumnCombo;
    private javax.swing.JPanel DeletePanel;
    private javax.swing.JTable DeleteTable;
    private javax.swing.JTextArea DescriptionField;
    private javax.swing.JLabel DescriptionLabel;
    private javax.swing.JButton DisableButton;
    private javax.swing.JButton EnableButton;
    private javax.swing.JTextField ImageField;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JTextField MonthField;
    private javax.swing.JLabel PreviewLabel;
    private javax.swing.JTextField PriceField;
    private javax.swing.JButton SaleButton;
    private javax.swing.JTable SaleTable;
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JTextArea TextField;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JPanel UpdatePanel;
    private javax.swing.JPanel ViewSalePanel;
    private javax.swing.JTextField YearField;
    private javax.swing.JComboBox<String> cardTypeCombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel preview2;
    // End of variables declaration//GEN-END:variables

}
