/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Website;

/**
 *
 * @author SHINU
 */

import Website.LoginFrame.UserSession;
import java.awt.BorderLayout;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
public class CardFrame extends javax.swing.JFrame {

    /**
     * Creates new form CardFrame
     */
    int id;
    public CardFrame(int id) {
        initComponents();
        this.id = id;
        fetchCardDetails(id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitlePanel = new javax.swing.JPanel();
        BackButton = new javax.swing.JButton();
        TitleLabel = new javax.swing.JLabel();
        CardPanel = new javax.swing.JPanel();
        CartButton = new javax.swing.JButton();
        NameLabel = new javax.swing.JLabel();
        PriceLabel = new javax.swing.JLabel();
        PriceDispLabel = new javax.swing.JLabel();
        DescriptionAreaLabel = new javax.swing.JLabel();
        DescriptionLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TitlePanel.setBackground(new java.awt.Color(207, 215, 255));

        BackButton.setBackground(new java.awt.Color(207, 215, 255));
        BackButton.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        BackButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\SHINU\\OneDrive\\문서\\miniproject\\wedding cards\\Icons\\backbtn.png")); // NOI18N
        BackButton.setText("BACK");
        BackButton.setBorder(null);
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        TitleLabel.setBackground(new java.awt.Color(207, 215, 255));
        TitleLabel.setFont(new java.awt.Font("Edwardian Script ITC", 1, 48)); // NOI18N
        TitleLabel.setForeground(new java.awt.Color(0, 0, 102));
        TitleLabel.setText("Geetha  RaniCards");
        TitleLabel.setOpaque(true);

        javax.swing.GroupLayout TitlePanelLayout = new javax.swing.GroupLayout(TitlePanel);
        TitlePanel.setLayout(TitlePanelLayout);
        TitlePanelLayout.setHorizontalGroup(
            TitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TitlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 786, Short.MAX_VALUE)
                .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        TitlePanelLayout.setVerticalGroup(
            TitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TitlePanelLayout.createSequentialGroup()
                .addGroup(TitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TitlePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TitlePanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(TitlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 70));

        CardPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout CardPanelLayout = new javax.swing.GroupLayout(CardPanel);
        CardPanel.setLayout(CardPanelLayout);
        CardPanelLayout.setHorizontalGroup(
            CardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        CardPanelLayout.setVerticalGroup(
            CardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        getContentPane().add(CardPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 360, 360));

        CartButton.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        CartButton.setText("ADD TO CART");
        CartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CartButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CartButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 650, 190, 40));
        getContentPane().add(NameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 300, 50));

        PriceLabel.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        PriceLabel.setText("PRICE :   ");
        getContentPane().add(PriceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, 80, 30));
        getContentPane().add(PriceDispLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 550, 70, 20));
        getContentPane().add(DescriptionAreaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 770, 350));

        DescriptionLabel.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        DescriptionLabel.setText("Description : ");
        getContentPane().add(DescriptionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1280, 840));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:    
            this.dispose();  
            new UserCardPage().setVisible(true); 
        
    }//GEN-LAST:event_BackButtonActionPerformed

    private void CartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CartButtonActionPerformed
        // TODO add your handling code here:
        try {
          
           String url = "jdbc:mysql://localhost:3306/project?useSSL=false&allowPublicKeyRetrieval=true";
           String user = "root";
           String password = "Shin@maya";

           Connection conn = DriverManager.getConnection(url, user, password);
           
           int userid = UserSession.currentUserId; 
           String name = NameLabel.getText();
           String cardName = name.replace("Name: ", "").trim(); // corrected
           System.out.println("Card Name: " + cardName);
           System.out.println("Card Name Length: " + cardName.length());


           String priceText = PriceDispLabel.getText().replaceAll("[^\\d.]", ""); 
           double price = Double.parseDouble(priceText);

           int quantity = 100; 
           double total = price * quantity;

           String query = "INSERT INTO cart (userid, card_id, name, price, quantity, total) VALUES (?, ?, ?, ?, ?, ?)";

           PreparedStatement pstmt = conn.prepareStatement(query);
           pstmt.setInt(1, userid);
           pstmt.setInt(2, id);
           pstmt.setString(3, cardName);
           pstmt.setDouble(4, price);
           pstmt.setInt(5, quantity);
           pstmt.setDouble(6, total);

           pstmt.executeUpdate();
           JOptionPane.showMessageDialog(this, "Card added to cart successfully!");

           conn.close();
        } catch (SQLException e) {
             JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage());
          } 

    

    }//GEN-LAST:event_CartButtonActionPerformed

    private void fetchCardDetails(int cardId) {
    Connection conn = null;
    PreparedStatement ps = null;
    ResultSet rs = null;

    try {
        
        conn = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/project?useSSL=false&allowPublicKeyRetrieval=true",
                "root", "Shin@maya");

        String sql = "SELECT * FROM cards WHERE card_id = ?";
        ps = conn.prepareStatement(sql);
        ps.setInt(1, cardId);
        rs = ps.executeQuery();

        if (rs.next()) {
            
            NameLabel.setText("Name: " + rs.getString("name"));
            NameLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 22));

            PriceDispLabel.setText("₹ " + rs.getFloat("price"));
            PriceDispLabel.setFont(new java.awt.Font("Segoe UI", 0, 18));

            String desc = rs.getString("descriptions");
            if (desc != null && !desc.isEmpty()) {
                DescriptionAreaLabel.setText("<html><p style=\"width:470px;\">" + desc + "</p></html>");
                DescriptionAreaLabel.setFont(new java.awt.Font("Segoe UI", 0, 16));
            }
            String imagePath = rs.getString("image_path");
            if (imagePath != null) {if (!imagePath.isEmpty()) {
                
                        ImageIcon icon = new ImageIcon(imagePath);
                        Image img = icon.getImage().getScaledInstance(360, 360, Image.SCALE_SMOOTH);
                        JLabel imageLabel = new JLabel(new ImageIcon(img));
                        imageLabel.setHorizontalAlignment(SwingConstants.CENTER);
                        
                        CardPanel.removeAll(); 
                        CardPanel.setLayout(new BorderLayout());
                        CardPanel.add(imageLabel, BorderLayout.CENTER);
                        CardPanel.revalidate();
                        CardPanel.repaint();
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Card not found.");
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
    } finally {
        try {
            if (rs != null) rs.close();
            if (ps != null) ps.close();
            if (conn != null) conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(CardFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JPanel CardPanel;
    private javax.swing.JButton CartButton;
    private javax.swing.JLabel DescriptionAreaLabel;
    private javax.swing.JLabel DescriptionLabel;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel PriceDispLabel;
    private javax.swing.JLabel PriceLabel;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JPanel TitlePanel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
