/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Website;

import java.util.*;
import java.awt.Color;
import javax.swing.JOptionPane;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.PreparedStatement;
/**
 *
 * @author SHINU
 */
public class SignUpFrame extends javax.swing.JFrame {
    register s = new register();
    /**
     * Creates new form SignUpFrame
     */
    public SignUpFrame() {
        initComponents();
    }
public static boolean isValidPassword(String password) {
        if (password == null || password.length() < 6) {
            return false; 
        }

        boolean hasUppercase = false;
        boolean hasLowercase = false;
        int digitCount = 0;

        for (char c : password.toCharArray()) {
            if (Character.isDigit(c)) {
                digitCount++;
            } else if (Character.isUpperCase(c)) {
                hasUppercase = true;
            } else if (Character.isLowerCase(c)) {
                hasLowercase = true;
            }
        }

        return digitCount >= 3 && hasUppercase && hasLowercase;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        SignUpPanel = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        UserNameLable = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        SignUPButton = new javax.swing.JButton();
        ShowCheckBox = new javax.swing.JCheckBox();
        PasswordField = new javax.swing.JPasswordField();
        UserNameField = new javax.swing.JTextField();
        EmailField = new javax.swing.JTextField();
        PhoneLabel = new javax.swing.JLabel();
        PhoneField = new javax.swing.JTextField();
        ConformPassLabel = new javax.swing.JLabel();
        ConformPasswordField = new javax.swing.JPasswordField();
        ConformCheckBox = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackButton.setBackground(new java.awt.Color(0, 0, 0, 0));
        BackButton.setBorder(null);
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, -1));

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\SHINU\\OneDrive\\문서\\miniproject\\wedding cards\\Icons\\backbtn.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 70, 30));

        SignUpPanel.setBackground(new java.awt.Color(255, 255, 255, 80));

        Title.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        Title.setText("SIGN UP");

        EmailLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        EmailLabel.setText("EMAIL ADDRESS");

        UserNameLable.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        UserNameLable.setText("USERNAME");

        PasswordLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        PasswordLabel.setText("PASSWORD");

        SignUPButton.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N
        SignUPButton.setText("SIGN UP");
        SignUPButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SignUPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUPButtonActionPerformed(evt);
            }
        });

        ShowCheckBox.setBackground(new java.awt.Color(204, 204, 204, 100));
        ShowCheckBox.setText("Show Password");
        ShowCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowCheckBoxActionPerformed(evt);
            }
        });

        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });

        UserNameField.setForeground(new java.awt.Color(204, 204, 204));
        UserNameField.setText("Enter User Name");
        UserNameField.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        UserNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UserNameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                UserNameFieldFocusLost(evt);
            }
        });
        UserNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameFieldActionPerformed(evt);
            }
        });

        EmailField.setForeground(new java.awt.Color(204, 204, 204));
        EmailField.setText("name@gmail.com");
        EmailField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EmailFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                EmailFieldFocusLost(evt);
            }
        });
        EmailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailFieldActionPerformed(evt);
            }
        });
        EmailField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EmailFieldKeyTyped(evt);
            }
        });

        PhoneLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        PhoneLabel.setText("PHONE NO.");

        PhoneField.setForeground(new java.awt.Color(204, 204, 204));
        PhoneField.setText("Enter Phone Number");
        PhoneField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PhoneFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PhoneFieldFocusLost(evt);
            }
        });
        PhoneField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneFieldActionPerformed(evt);
            }
        });

        ConformPassLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        ConformPassLabel.setText("CONFORM PASSWORD");

        ConformCheckBox.setText("Show Password");
        ConformCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConformCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SignUpPanelLayout = new javax.swing.GroupLayout(SignUpPanel);
        SignUpPanel.setLayout(SignUpPanelLayout);
        SignUpPanelLayout.setHorizontalGroup(
            SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SignUpPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(UserNameField)
                        .addComponent(PasswordField)
                        .addComponent(ConformPasswordField)
                        .addComponent(PhoneField, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE))
                    .addComponent(ShowCheckBox)
                    .addComponent(ConformCheckBox)
                    .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73))
            .addGroup(SignUpPanelLayout.createSequentialGroup()
                .addGroup(SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SignUpPanelLayout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addGroup(SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SignUPButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(SignUpPanelLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UserNameLable, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PhoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ConformPassLabel))))
                .addContainerGap(328, Short.MAX_VALUE))
        );
        SignUpPanelLayout.setVerticalGroup(
            SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignUpPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailLabel)
                    .addComponent(EmailField))
                .addGap(34, 34, 34)
                .addGroup(SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserNameLable)
                    .addComponent(UserNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ShowCheckBox)
                .addGap(23, 23, 23)
                .addGroup(SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConformPassLabel)
                    .addComponent(ConformPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ConformCheckBox)
                .addGap(18, 18, 18)
                .addComponent(SignUPButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(204, 204, 204))
        );

        getContentPane().add(SignUpPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 740, 550));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\SHINU\\OneDrive\\문서\\miniproject\\wedding cards\\Background\\login & signin.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -110, 1310, 910));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SignUPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUPButtonActionPerformed
        // TODO add your handling code here:
        String username = UserNameField.getText();
        String email = EmailField.getText();
        String password;
        password = new String(PasswordField.getPassword());

        if (email.isEmpty() || username.isEmpty() || password.isEmpty() || PhoneField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields are required!", "Error", JOptionPane.ERROR_MESSAGE);
            
        }
        else if (!email.matches("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-z]{2,6}$")) {
            JOptionPane.showMessageDialog(this, "Invalid Email Address", "Error", JOptionPane.ERROR_MESSAGE);
            
        }
        else if (!isValidPassword(password)) {
            JOptionPane.showMessageDialog(this, "Requirement:Atleast 6 characters,1 Uppercase,1 Lowercase", "Error", JOptionPane.ERROR_MESSAGE);
            
        }
        else if (PhoneField.getText().length() != 10){
            JOptionPane.showMessageDialog(this, "Invalid Phone number", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            s.reg();
        }      
    }//GEN-LAST:event_SignUPButtonActionPerformed

    private void ShowCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowCheckBoxActionPerformed
        // TODO add your handling code here:
        ShowCheckBox.setBackground(SignUpPanel.getBackground());
        if(ShowCheckBox.isSelected()){
            PasswordField.setEchoChar((char) 0); //show password
        }
        else{
            PasswordField.setEchoChar('*');//Hide Password
        }
    }//GEN-LAST:event_ShowCheckBoxActionPerformed

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldActionPerformed

    private void UserNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UserNameFieldFocusGained
        // TODO add your handling code here:
        if(UserNameField.getText().equals("Enter User Name")){
            UserNameField.setText("");
            UserNameField.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_UserNameFieldFocusGained

    private void UserNameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UserNameFieldFocusLost
        // TODO add your handling code here:
        if(UserNameField.getText().isEmpty()){
            UserNameField.setText("Enter User Name");
            UserNameField.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_UserNameFieldFocusLost

    private void UserNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNameFieldActionPerformed

    private void EmailFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmailFieldFocusGained
        // TODO add your handling code here:
        if(EmailField.getText().equals("name@gmail.com")){
            EmailField.setText("");
            EmailField.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_EmailFieldFocusGained

    private void EmailFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmailFieldFocusLost
        // TODO add your handling code here:
        if(EmailField.getText().isEmpty()){
            EmailField.setText("name@gmail.com");
            EmailField.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_EmailFieldFocusLost

    private void EmailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailFieldActionPerformed

    private void EmailFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmailFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailFieldKeyTyped

    private void PhoneFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PhoneFieldFocusGained
        // TODO add your handling code here:
        if(PhoneField.getText().trim().equals("Enter Phone Number")){
            PhoneField.setText("");
            PhoneField.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_PhoneFieldFocusGained

    private void PhoneFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PhoneFieldFocusLost
        // TODO add your handling code here:
        if(PhoneField.getText().trim().isEmpty()){
            PhoneField.setText("Enter Phone Number");
            PhoneField.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_PhoneFieldFocusLost

    private void PhoneFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneFieldActionPerformed

    private void ConformCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConformCheckBoxActionPerformed
        // TODO add your handling code here:
        if(ConformCheckBox.isSelected()){
            ConformPasswordField.setEchoChar((char) 0); //show password
        }
        else{
            ConformPasswordField.setEchoChar('*');//Hide Password
        }
    }//GEN-LAST:event_ConformCheckBoxActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();  
        new MainFrame().setVisible(true); 
    }//GEN-LAST:event_BackButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

        public class register{
        private Connection conn ;
        public register(){
             connectToDatabase();
        }    
    public void connectToDatabase() {
        try {
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            
            String url = "jdbc:mysql://localhost:3306/project?useSSL=false&allowPublicKeyRetrieval=true";  
            String user = "root"; 
            String password = "Shin@maya";  
           
            conn = DriverManager.getConnection(url, user, password);
            System.out.println("Connected successfully!");
            JOptionPane.showMessageDialog(null, "Database connected successfully!");

        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, "MySQL JDBC Driver not found!");
            e.printStackTrace();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Database connection failed!\n" + e.getMessage());
            e.printStackTrace();
        }
    }
    
    public boolean isUserSignedIn(String email) {
    boolean isSignedIn = false;
    try {
        String query = "SELECT * FROM users WHERE emailid = ?";
        PreparedStatement ps = conn.prepareStatement(query);
        ps.setString(1, email);
        
        ResultSet rs = ps.executeQuery();
        
        if (rs.next()) {
            isSignedIn = true;
        }
        
        rs.close();
        ps.close();
    } catch (Exception e) {
        e.printStackTrace();
    }
    return isSignedIn;
}

public void reg() {
    String username = UserNameField.getText();
    String gmail = EmailField.getText();
    String phnno = PhoneField.getText();
    String password = new String(PasswordField.getPassword());
    String role = "customer";
    
    try {
        if (isUserSignedIn(gmail)) {
            JOptionPane.showMessageDialog(null, "Mail id already in use!");
        } else {
            String query = "INSERT INTO users(username, password, emailid, phone, roles) VALUES (?, ?, ?, ?, ?)";
            PreparedStatement pt = conn.prepareStatement(query);
            pt.setString(1, username);
            pt.setString(2, password);
            pt.setString(3, gmail);
            pt.setString(4, phnno);
            pt.setString(5, role);
            pt.executeUpdate();
            pt.close();
            JOptionPane.showMessageDialog(null, "Registered successfully!");
            MainFrame m = new MainFrame();
            m.show();
            dispose();
            
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Registration failed!\n" + e.getMessage());
        e.printStackTrace();
    }
}

        }   
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JCheckBox ConformCheckBox;
    private javax.swing.JLabel ConformPassLabel;
    private javax.swing.JPasswordField ConformPasswordField;
    private javax.swing.JTextField EmailField;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JTextField PhoneField;
    private javax.swing.JLabel PhoneLabel;
    private javax.swing.JCheckBox ShowCheckBox;
    private javax.swing.JButton SignUPButton;
    private javax.swing.JPanel SignUpPanel;
    private javax.swing.JLabel Title;
    private javax.swing.JTextField UserNameField;
    private javax.swing.JLabel UserNameLable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
